package main

import (
	"Facility38/def"
	"Facility38/world"
)

/* World objects and images */
var WorldObjs = []*world.ObjType{
	//Game Objects
	{
		Base:        "basic-miner",
		Name:        "Basic Miner",
		Description: "Mines solid resources where placed, requires coal fuel",
		TypeI:       def.ObjTypeBasicMiner,
		Category:    def.ObjCatGeneric,
		Size:        world.XYs{X: 2, Y: 2},
		UpdateObj:   minerUpdate,
		InitObj:     initMiner,
		DeInitObj:   deinitMiner,
		LinkObj:     linkMiner,
		MachineSettings: world.MachineData{
			KgHourMine: 1000,
			KW:         360,
		},
		TockInterval: uint8(world.ObjectUPS/2) * 5,
		ShowArrow:    true,
		ToolBarArrow: true,
		Symbol:       "MIN",
		Ports: []world.ObjPortData{
			{Dir: def.DIR_NORTH, Type: def.PORT_OUT},

			/* Fuel inputs */
			{Dir: def.DIR_NORTH, Type: def.PORT_FIN},
			{Dir: def.DIR_EAST, Type: def.PORT_FIN},
			{Dir: def.DIR_SOUTH, Type: def.PORT_FIN},
			{Dir: def.DIR_WEST, Type: def.PORT_FIN},
		},
		SubObjs: []world.XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},

	{
		Base:        "basic-belt",
		Name:        "Basic Belt",
		Description: "Moves items from rear and sides,\nin direction of arrow",
		TypeI:       def.ObjTypeBasicBelt,
		Category:    def.ObjCatBelt,
		Size:        world.XYs{X: 1, Y: 1},
		Rotatable:   true,
		UpdateObj:   beltUpdate,
		LinkObj:     linkBelt,
		Symbol:      "BLT",
		Ports: []world.ObjPortData{
			{Dir: def.DIR_NORTH, Type: def.PORT_OUT},
			{Dir: def.DIR_EAST, Type: def.PORT_IN},
			{Dir: def.DIR_SOUTH, Type: def.PORT_IN},
			{Dir: def.DIR_WEST, Type: def.PORT_IN},
		},
	},
	{
		Base:        "basic-belt-over",
		Name:        "Basic Belt Overpass",
		Description: "A belt with an underpass",
		TypeI:       def.ObjTypeBasicBeltOver,
		Category:    def.ObjCatBelt,
		Size:        world.XYs{X: 1, Y: 3},
		Rotatable:   true,
		UpdateObj:   beltUpdateOver,
		InitObj:     initBeltOver,
		LinkObj:     linkBeltOver,
		Symbol:      "BOP",
		Ports: []world.ObjPortData{
			/* Overpass is one direction */
			{Dir: def.DIR_NORTH, Type: def.PORT_OUT},
			{Dir: def.DIR_SOUTH, Type: def.PORT_IN},

			/* Underpass is bidirectional */
			{Dir: def.DIR_WEST, Type: def.PORT_OUT},
			{Dir: def.DIR_EAST, Type: def.PORT_OUT},
			{Dir: def.DIR_WEST, Type: def.PORT_IN},
			{Dir: def.DIR_EAST, Type: def.PORT_IN},
		},
		SubObjs: []world.XYs{{X: 0, Y: 0}, {X: 0, Y: 1}, {X: 0, Y: 2}},
	},

	{
		Base:         "basic-splitter",
		Name:         "Basic Splitter",
		Description:  "Input from back outputs\nequally to up to 3 outputs",
		TypeI:        def.ObjTypeBasicSplit,
		Category:     def.ObjCatBelt,
		Size:         world.XYs{X: 1, Y: 1},
		ShowArrow:    true,
		ToolBarArrow: true,
		MachineSettings: world.MachineData{
			KW: 100,
		},
		UpdateObj: splitterUpdate,
		LinkObj:   linkSplitter,
		Symbol:    "SPT",
		Ports: []world.ObjPortData{
			{Dir: def.DIR_NORTH, Type: def.PORT_OUT},
			{Dir: def.DIR_EAST, Type: def.PORT_OUT},
			{Dir: def.DIR_WEST, Type: def.PORT_OUT},
			{Dir: def.DIR_SOUTH, Type: def.PORT_IN},
		},
	},

	{
		Base:        "basic-box",
		Name:        "Basic Box",
		Description: "Currently only stores objects\n(no unloader yet)",
		TypeI:       def.ObjTypeBasicBox,
		Category:    def.ObjCatGeneric,
		Size:        world.XYs{X: 2, Y: 2},
		MachineSettings: world.MachineData{
			MaxContainKG: 1000,
		},
		Symbol:       "BOX",
		UpdateObj:    boxUpdate,
		LinkObj:      linkBox,
		TockInterval: uint8(world.ObjectUPS/2) * 1,
		CanContain:   true,
		ToolBarArrow: false,
		Ports: []world.ObjPortData{
			{Dir: def.DIR_NORTH, Type: def.PORT_IN},
			{Dir: def.DIR_EAST, Type: def.PORT_IN},
			{Dir: def.DIR_SOUTH, Type: def.PORT_IN},
			{Dir: def.DIR_WEST, Type: def.PORT_IN},

			{Dir: def.DIR_NORTH, Type: def.PORT_OUT},
			{Dir: def.DIR_EAST, Type: def.PORT_OUT},
			{Dir: def.DIR_SOUTH, Type: def.PORT_OUT},
			{Dir: def.DIR_WEST, Type: def.PORT_OUT},
		},
		SubObjs: []world.XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},

	{
		Base:        "basic-smelter",
		Name:        "Basic Smelter",
		Description: "Bakes solid ores into metal or stone\nbricks, requires coal fuel",
		TypeI:       def.ObjTypeBasicSmelter,
		Category:    def.ObjCatGeneric,
		Size:        world.XYs{X: 2, Y: 2},
		MachineSettings: world.MachineData{
			KW:         320,
			KgHourMine: 40,
		},
		TockInterval: uint8(world.ObjectUPS/2) * 30,
		ShowArrow:    true,
		ToolBarArrow: true,
		Symbol:       "SMT",
		UpdateObj:    smelterUpdate,
		InitObj:      initSmelter,
		LinkObj:      linkMachine,
		Ports: []world.ObjPortData{
			{Dir: def.DIR_NORTH, Type: def.PORT_OUT},
			{Dir: def.DIR_SOUTH, Type: def.PORT_IN},

			{Dir: def.DIR_EAST, Type: def.PORT_FIN},
			{Dir: def.DIR_WEST, Type: def.PORT_FIN},
		},
		SubObjs: []world.XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},

	{
		Base:        "basic-caster",
		Name:        "Basic Caster",
		Description: "Casts metal shot into bars",
		TypeI:       def.ObjTypeBasicCaster,
		Category:    def.ObjCatGeneric,
		Size:        world.XYs{X: 2, Y: 2},
		MachineSettings: world.MachineData{
			KW:         320,
			KgHourMine: 40,
		},
		TockInterval: uint8(world.ObjectUPS/2) * 15,
		ShowArrow:    true,
		ToolBarArrow: true,
		Symbol:       "CST",
		UpdateObj:    casterUpdate,
		InitObj:      initSmelter,
		LinkObj:      linkMachine,
		Ports: []world.ObjPortData{
			{Dir: def.DIR_NORTH, Type: def.PORT_OUT},
			{Dir: def.DIR_SOUTH, Type: def.PORT_IN},

			{Dir: def.DIR_EAST, Type: def.PORT_FIN},
			{Dir: def.DIR_WEST, Type: def.PORT_FIN},
		},
		SubObjs: []world.XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},

	{
		Base:        "basic-rod-caster",
		Name:        "Basic Rod Caster",
		Description: "Casts metal bars into rods",
		TypeI:       def.ObjTypeBasicRodCaster,
		Category:    def.ObjCatGeneric,
		Size:        world.XYs{X: 2, Y: 2},
		MachineSettings: world.MachineData{
			KW:         320,
			KgHourMine: 40,
		},
		TockInterval: uint8(world.ObjectUPS/2) * 15,
		ShowArrow:    true,
		ToolBarArrow: true,
		Symbol:       "ROD",
		UpdateObj:    rodCasterUpdate,
		InitObj:      initSmelter,
		LinkObj:      linkMachine,
		Ports: []world.ObjPortData{
			{Dir: def.DIR_NORTH, Type: def.PORT_OUT},
			{Dir: def.DIR_SOUTH, Type: def.PORT_IN},

			{Dir: def.DIR_EAST, Type: def.PORT_FIN},
			{Dir: def.DIR_WEST, Type: def.PORT_FIN},
		},
		SubObjs: []world.XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},
	{
		Base:        "basic-slip-roller",
		Name:        "Basic Slip Roller",
		Description: "Press metal bar into sheets",
		TypeI:       def.ObjTypeBasicSlipRoller,
		Category:    def.ObjCatGeneric,
		Size:        world.XYs{X: 2, Y: 2},
		UpdateObj:   slipRollerUpdate,
		InitObj:     initSlipRoller,
		LinkObj:     linkMachine,
		MachineSettings: world.MachineData{
			KW:         10,
			KgHourMine: 40,
		},
		TockInterval: uint8(world.ObjectUPS/2) * 15,
		Symbol:       "SR",
		Ports: []world.ObjPortData{
			{Dir: def.DIR_NORTH, Type: def.PORT_OUT},
			{Dir: def.DIR_SOUTH, Type: def.PORT_IN},
		},
		ShowArrow:    true,
		ToolBarArrow: true,
		SubObjs:      []world.XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},
	{
		Base:        "basic-fuel-hopper",
		Name:        "Basic Fuel Hopper",
		Description: "Loads soild fuel into machines",
		TypeI:       def.ObjTypeBasicFuelHopper,
		Category:    def.ObjCatLoader,
		Size:        world.XYs{X: 1, Y: 1},
		Rotatable:   true,
		ShowArrow:   false,
		UpdateObj:   fuelHopperUpdate,
		LinkObj:     linkFuelHopper,
		MachineSettings: world.MachineData{
			KW:           10,
			KgHopperMove: 1,
		},
		TockInterval: uint8(world.ObjectUPS/2) * 2,
		Symbol:       "FHP",
		Ports: []world.ObjPortData{
			{Dir: def.DIR_NORTH, Type: def.PORT_IN},
			{Dir: def.DIR_EAST, Type: def.PORT_IN},
			{Dir: def.DIR_WEST, Type: def.PORT_IN},
			{Dir: def.DIR_SOUTH, Type: def.PORT_FOUT},
		},
	},
	{
		Base:        "basic-unloader",
		Name:        "Basic Unloader",
		Description: "Unloads Material",
		TypeI:       def.ObjTypeBasicUnloader,
		Category:    def.ObjCatLoader,
		Size:        world.XYs{X: 1, Y: 1},
		Rotatable:   true,
		UpdateObj:   loaderUpdate,
		LinkObj:     linkUnloader,
		MachineSettings: world.MachineData{
			KW:           10,
			KgHopperMove: 1,
		},
		TockInterval: 0,
		Symbol:       "ULD",
		Ports: []world.ObjPortData{
			{Dir: def.DIR_NORTH, Type: def.PORT_OUT},
			{Dir: def.DIR_SOUTH, Type: def.PORT_IN},
		},
	},
	{
		Base:        "basic-loader",
		Name:        "Basic Loader",
		Description: "Loads Material",
		TypeI:       def.ObjTypeBasicLoader,
		Category:    def.ObjCatLoader,
		Size:        world.XYs{X: 1, Y: 1},
		Rotatable:   true,
		ShowArrow:   false,
		UpdateObj:   loaderUpdate,
		LinkObj:     linkUnloader,
		MachineSettings: world.MachineData{
			KW:           10,
			KgHopperMove: 1,
		},
		TockInterval: 0,
		Symbol:       "LD",
		Ports: []world.ObjPortData{
			{Dir: def.DIR_NORTH, Type: def.PORT_OUT},
			{Dir: def.DIR_SOUTH, Type: def.PORT_IN},
		},
	},
}
