package main

/* World objects and images */
var worldObjs = []*objType{
	//Game Objects
	{
		base:        "basic-miner",
		name:        "Basic Miner",
		description: "Mines solid resources where placed",
		typeI:       objTypeBasicMiner,
		category:    objCatGeneric,
		size:        XYs{X: 2, Y: 2},
		updateObj:   minerUpdate,
		initObj:     initMiner,
		deInitObj:   deinitMiner,
		linkObj:     linkMiner,
		machineSettings: machineData{
			kgHourMine: 1000,
			kw:         360,
		},
		tockInterval: uint8(ObjectUPS/2) * 5,
		symbol:       "MIN",
		ports: []ObjPortData{
			{Dir: DIR_ANY, Type: PORT_OUT},

			/* Fuel inputs */
			{Dir: DIR_ANY, Type: PORT_FIN},
		},
		subObjs: []XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},

	{
		base:        "basic-belt",
		name:        "Basic Belt",
		description: "Moves material from rear and sides forward",
		typeI:       objTypeBasicBelt,
		category:    objCatBelt,
		size:        XYs{X: 1, Y: 1},
		rotatable:   true,
		updateObj:   beltUpdate,
		linkObj:     linkBelt,
		symbol:      "BLT",
		ports: []ObjPortData{
			{Dir: DIR_NORTH, Type: PORT_OUT},
			{Dir: DIR_EAST, Type: PORT_IN},
			{Dir: DIR_SOUTH, Type: PORT_IN},
			{Dir: DIR_WEST, Type: PORT_IN},
		},
	},
	{
		base:        "basic-belt-over",
		name:        "Basic Belt Overpass",
		description: "Belt with an underpass",
		typeI:       objTypeBasicBeltOver,
		category:    objCatBelt,
		size:        XYs{X: 1, Y: 3},
		rotatable:   true,
		updateObj:   beltUpdateOver,
		initObj:     initBeltOver,
		linkObj:     linkBeltOver,
		symbol:      "BOP",
		ports: []ObjPortData{
			/* Overpass is one direction */
			{Dir: DIR_NORTH, Type: PORT_OUT},
			{Dir: DIR_SOUTH, Type: PORT_IN},

			/* Underpass is bidirectional */
			{Dir: DIR_WEST, Type: PORT_OUT},
			{Dir: DIR_EAST, Type: PORT_OUT},
			{Dir: DIR_WEST, Type: PORT_IN},
			{Dir: DIR_EAST, Type: PORT_IN},
		},
		subObjs: []XYs{{X: 0, Y: 0}, {X: 0, Y: 1}, {X: 0, Y: 2}},
	},

	{
		base:         "basic-splitter",
		name:         "Basic Splitter",
		description:  "One input belt to three output belts.",
		typeI:        objTypeBasicSplit,
		category:     objCatBelt,
		size:         XYs{X: 1, Y: 1},
		showArrow:    true,
		toolBarArrow: true,
		machineSettings: machineData{
			kw: 100,
		},
		updateObj: splitterUpdate,
		linkObj:   linkSplitter,
		symbol:    "SPT",
		ports: []ObjPortData{
			{Dir: DIR_NORTH, Type: PORT_OUT},
			{Dir: DIR_EAST, Type: PORT_OUT},
			{Dir: DIR_WEST, Type: PORT_OUT},
			{Dir: DIR_SOUTH, Type: PORT_IN},
		},
	},

	{
		base:        "basic-box",
		name:        "Basic Box",
		description: "Stores 1 ton\n(No unloader yet)",
		typeI:       objTypeBasicBox,
		category:    objCatGeneric,
		size:        XYs{X: 2, Y: 2},
		machineSettings: machineData{
			maxContainKG: 1000,
		},
		symbol:       "BOX",
		updateObj:    boxUpdate,
		linkObj:      linkBox,
		tockInterval: uint8(ObjectUPS/2) * 1,
		canContain:   true,
		ports: []ObjPortData{
			{Dir: DIR_ANY, Type: PORT_IN},
			{Dir: DIR_ANY, Type: PORT_OUT},
		},
		subObjs: []XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},

	{
		base:        "basic-smelter",
		name:        "Basic Smelter",
		description: "Solid ores into metals or stone",
		typeI:       objTypeBasicSmelter,
		category:    objCatGeneric,
		size:        XYs{X: 2, Y: 2},
		machineSettings: machineData{
			kw:         320,
			kgHourMine: 40,
		},
		tockInterval: uint8(ObjectUPS/2) * 30,
		symbol:       "SMT",
		updateObj:    smelterUpdate,
		initObj:      initSmelter,
		linkObj:      linkMachine,
		ports: []ObjPortData{
			{Dir: DIR_ANY, Type: PORT_OUT},
			{Dir: DIR_ANY, Type: PORT_IN},

			{Dir: DIR_ANY, Type: PORT_FIN},
		},
		subObjs: []XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},

	{
		base:        "basic-caster",
		name:        "Basic Caster",
		description: "Metal shot into bars",
		typeI:       objTypeBasicCaster,
		category:    objCatGeneric,
		size:        XYs{X: 2, Y: 2},
		machineSettings: machineData{
			kw:         320,
			kgHourMine: 40,
		},
		tockInterval: uint8(ObjectUPS/2) * 15,
		symbol:       "CST",
		updateObj:    casterUpdate,
		initObj:      initSmelter,
		linkObj:      linkMachine,
		ports: []ObjPortData{
			{Dir: DIR_ANY, Type: PORT_OUT},
			{Dir: DIR_ANY, Type: PORT_IN},
			{Dir: DIR_ANY, Type: PORT_FIN},
		},
		subObjs: []XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},

	{
		base:        "basic-rod-caster",
		name:        "Basic Rod Caster",
		description: "Metal bars into rods",
		typeI:       objTypeBasicRodCaster,
		category:    objCatGeneric,
		size:        XYs{X: 2, Y: 2},
		machineSettings: machineData{
			kw:         320,
			kgHourMine: 40,
		},
		tockInterval: uint8(ObjectUPS/2) * 15,
		symbol:       "ROD",
		updateObj:    rodCasterUpdate,
		initObj:      initSmelter,
		linkObj:      linkMachine,
		ports: []ObjPortData{
			{Dir: DIR_ANY, Type: PORT_OUT},
			{Dir: DIR_ANY, Type: PORT_IN},
			{Dir: DIR_ANY, Type: PORT_FIN},
		},
		subObjs: []XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},
	{
		base:        "basic-slip-roller",
		name:        "Basic Slip Roller",
		description: "Metal bars into sheets",
		typeI:       objTypeBasicSlipRoller,
		category:    objCatGeneric,
		size:        XYs{X: 2, Y: 2},
		updateObj:   slipRollerUpdate,
		initObj:     initSlipRoller,
		linkObj:     linkMachine,
		machineSettings: machineData{
			kw:         10,
			kgHourMine: 40,
		},
		tockInterval: uint8(ObjectUPS/2) * 15,
		symbol:       "SR",
		ports: []ObjPortData{
			{Dir: DIR_ANY, Type: PORT_OUT},
			{Dir: DIR_ANY, Type: PORT_IN},
			{Dir: DIR_ANY, Type: PORT_FIN},
		},
		subObjs: []XYs{{X: 0, Y: 0}, {X: 1, Y: 0}, {X: 0, Y: 1}, {X: 1, Y: 1}},
	},
	{
		base:        "basic-fuel-hopper",
		name:        "Basic Fuel Hopper",
		description: "Solid Fuel loader",
		typeI:       objTypeBasicFuelHopper,
		category:    objCatLoader,
		size:        XYs{X: 1, Y: 1},
		rotatable:   true,
		showArrow:   false,
		updateObj:   fuelHopperUpdate,
		linkObj:     linkFuelHopper,
		machineSettings: machineData{
			kw:           10,
			kgHopperMove: 1,
		},
		tockInterval: uint8(ObjectUPS/2) * 5,
		symbol:       "FHP",
		ports: []ObjPortData{
			{Dir: DIR_ANY, Type: PORT_IN},
			{Dir: DIR_EAST, Type: PORT_IN},
			{Dir: DIR_WEST, Type: PORT_IN},
			{Dir: DIR_SOUTH, Type: PORT_FOUT},
		},
	},
	{
		base:        "basic-unloader",
		name:        "Basic Unloader",
		description: "Unloads to belts",
		typeI:       objTypeBasicUnloader,
		category:    objCatLoader,
		size:        XYs{X: 1, Y: 1},
		rotatable:   true,
		updateObj:   loaderUpdate,
		linkObj:     linkUnloader,
		machineSettings: machineData{
			kw:           10,
			kgHopperMove: 1,
		},
		tockInterval: 0,
		symbol:       "ULD",
		ports: []ObjPortData{
			{Dir: DIR_NORTH, Type: PORT_OUT},
			{Dir: DIR_SOUTH, Type: PORT_IN},
		},
	},
	{
		base:        "basic-loader",
		name:        "Basic Loader",
		description: "Loads from belts",
		typeI:       objTypeBasicLoader,
		category:    objCatLoader,
		size:        XYs{X: 1, Y: 1},
		rotatable:   true,
		showArrow:   false,
		updateObj:   loaderUpdate,
		linkObj:     linkUnloader,
		machineSettings: machineData{
			kw:           10,
			kgHopperMove: 1,
		},
		tockInterval: 0,
		symbol:       "LD",
		ports: []ObjPortData{
			{Dir: DIR_NORTH, Type: PORT_OUT},
			{Dir: DIR_SOUTH, Type: PORT_IN},
		},
	},
}
